# Alle teksten van de site, per taal (nl = Nederlands, en = Engels, de = Duits).
# Alleen feiten die de familie zelf heeft gegeven; verzin hier niets bij.
# Na een wijziging: python3 build.py  (maakt docs/ opnieuw; zie README voor een eigen domein).

COMPANY = {
    "name": "Roots",
    "legal_name": "@Roots",
    "street": "Hartogsweg 18",
    "postcode": "8271 PE",
    "city": "IJsselmuiden",
    "country": "NL",
    "phone_e164": "+31645628490",
    "phone_nl": "06 45 62 84 90",
    "phone_intl": "+31 6 45 62 84 90",
    "email": "greenatroots@gmail.com",
    "kvk": "84525762",
    "founded": "2021",
    "plantipp": "https://plantipp.eu/nl/growers/roots",
}

LANGS = ["nl", "en", "de"]
LANG_NAMES = {"nl": "Nederlands", "en": "English", "de": "Deutsch"}
OG_LOCALE = {"nl": "nl_NL", "en": "en_GB", "de": "de_DE"}

# Ankers per taal (homepage-secties)
IDS = {
    "nl": {"process": "werkwijze", "plants": "planten", "about": "over-ons", "buy": "inkopen", "faq": "vragen", "contact": "contact"},
    "en": {"process": "how-we-grow", "plants": "plants", "about": "about-us", "buy": "buying", "faq": "faq", "contact": "contact"},
    "de": {"process": "anbau", "plants": "pflanzen", "about": "ueber-uns", "buy": "einkauf", "faq": "fragen", "contact": "kontakt"},
}

T = {
# ------------------------------------------------------------------ NEDERLANDS
"nl": {
    "skip": "Naar de inhoud",
    "brand_label": "Roots, naar de homepage",
    "menu_label": "Hoofdmenu",
    "lang_label": "Taal",
    "nav": {"process": "Werkwijze", "plants": "Planten", "about": "Over ons", "buy": "Inkopen"},
    "contact_btn": "Contact",
    "home_title": "Roots | Sempervivum-kwekerij in IJsselmuiden",
    "home_desc": "Roots kweekt Sempervivum (Chick Charms®, Giants, Colorockz®), Perovskia en Hibiscus in IJsselmuiden. Sempervivum van eigen stek, verkocht via Royal FloraHolland of direct.",
    "badge": "Kwekerij in IJsselmuiden · sinds 2021",
    "h1": "Sterke succulenten voor je assortiment.",
    "lede": "Sempervivum, Perovskia en Hibiscus van eigen kwekerij. Koop via Royal FloraHolland of direct bij ons.",
    "cta_plants": "Bekijk de planten",
    "cta_buy": "Zo koop je bij ons",
    "ticker_label": "Wat we kweken",
    # werkwijze
    "proc_h2": "Van stek tot klant",
    "proc_scribble": "de grond in, de kas uit",
    "proc_intro": "Een goede wortel eerst, de rest volgt. Klik op een stap voor meer.",
    "group_in": "De kas in",
    "group_out": "De kas uit",
    "steps": [
        {"title": "Eigen stek", "chips": [], "text": "Onze succulenten beginnen als stek die we zelf maken."},
        {"title": "Wortelen", "chips": [], "text": "Een stek krijgt eerst de tijd voor een sterk wortelgestel, vandaar onze naam.",
         "alt": "Een geworteld stekje Sempervivum in de hand, met de wortels zichtbaar, boven een tafel vol jonge plantjes"},
        {"title": "Oppotten", "chips": ["Pot 12–18 cm"], "text": "Daarna gaat de plant over naar zijn eindpot.",
         "alt": "Een Sempervivum in pot in de hand, met een kastafel vol planten erachter"},
        {"title": "Groeien in de kas", "chips": ["6–8 maanden", "Mineralen en mest"], "text": "In onze kas in IJsselmuiden groeit de plant uit.",
         "alt": "Een rood-gele Sempervivum in pot, met een kas vol dezelfde planten erachter"},
        {"title": "Klaarmaken", "chips": [], "text": "Is de plant volgroeid, dan maken we hem klaar voor de order.",
         "alt": "Een kar vol Sempervivum in trays, met etiketten, klaar voor de order"},
        {"title": "Veiling of direct", "chips": ["Floriday", "Direct"], "text": "We verkopen via de veiling van Royal FloraHolland of direct aan de koper.",
         "alt": "Verkoopklare Sempervivum in pot op de kastafel"},
        {"title": "Onderweg", "chips": [], "text": "Via de veiling gaat de plant de distributie in, onder meer naar Scandinavië, Engeland, Duitsland en Zuid-Europa.",
         "alt": "Een vrachtwagen voor bloementransport bij de kwekerij, in het ochtendlicht"},
    ],
    # planten
    "plants_h2": "Onze planten",
    "plants_scribble": "Sempervivum voorop",
    "plants_intro": "Sempervivum is ons hoofdproduct. In het seizoen kweken we ook Perovskia en Hibiscus.",
    "prev": "Vorige planten",
    "next": "Volgende planten",
    "cards_label": "Planten",
    "credit": "Plantfoto's: Plantipp",
    "series": {
        "chick-charms": {"name": "Chick Charms®", "tag": "Sempervivum", "text": "Sempervivum in veel kleuren.", "alt": "Sempervivum Chick Charms Gold Rush: rozetten in goud en rood"},
        "giants": {"name": "Chick Charms® Giants", "tag": "Sempervivum", "text": "Chick Charms met extra grote rozetten.", "alt": "Sempervivum Chick Charms Giants Emerald Explosion: grote rozet in een groene pot"},
        "colorockz": {"name": "Colorockz®", "tag": "Sempervivum", "text": "Sterke Sempervivum die met de seizoenen van kleur verandert.", "alt": "Sempervivum Colorockz Lemon Flare: volle rozetten in groen met rode punten"},
        "perovskia": {"name": "Perovskia", "tag": "Mei – september", "text": "Russische salie met lavendelpaarse bloei.", "alt": "Perovskia Prime Time: Russische salie met lavendelpaarse bloei"},
        "hibiscus": {"name": "Hibiscus", "tag": "Zomer", "text": "Zomerbloeier met grote bloemen.", "alt": "Hibiscus met grote witte bloem"},
    },
    # over ons
    "about_h2": "Onze roots",
    "about_scribble": "opgegroeid in de tuinbouw",
    "about_p": "Stefan en Christel begonnen Roots in 2021. In 2022 kochten ze de kas aan de Hartogsweg in IJsselmuiden.",
    "about_more": "Lees ons verhaal",
    "about_story": "Stefan groeide op in de tuinbouw: op een rozenkwekerij van 600.000 m² en in de tuinbouw in Afrika. Samen begonnen ze klein, maar al snel stond de kas vol. Die groei ging nooit ten koste van de kwaliteit: van de eerste stek tot de plant op de kar letten ze op elk detail.",
    "people": [
        {"name": "Stefan", "role": "Eigenaar", "text": "Dagelijkse leiding, groei, strategie, verkoop, inkoop en personeel."},
        {"name": "Christel", "role": "Compagnon", "text": "Strategie en boekhouding."},
    ],
    "about_small": "In de drukke maanden werken scholieren en seizoenskrachten met ons mee.",
    "about_alt": "Stefan en Christel bij de kas, met Perovskia in pot",
    # inkopen
    "buy_h2": "Zo koop je bij ons",
    "buy_scribble": "veiling of direct",
    "buy_cards": [
        {"title": "Via de veiling", "text": "Koop via Royal FloraHolland: daarvoor ben je lid, bestellen gaat via Floriday."},
        {"title": "Direct", "text": "Bel of mail ons voor wat er nu in de kas staat."},
        {"title": "Maatwerk", "text": "Neem contact op voor iets op maat, zakelijk of particulier."},
    ],
    "dest_label": "Onze planten gaan onder meer naar",
    "dest": {"n": ("Scandinavië", "Noord"), "w": ("Engeland", "West"), "e": ("Duitsland", "Oost"), "s": ("Zuid-Europa", "Zuid")},
    # vragen
    "faq_h2": "Goed om te weten",
    "faq": [
        ("Kan ik als particulier bij jullie kopen?", "Bijna niet: onze kopers zijn vooral zakelijke inkopers. Zoek je iets op maat, als particulier of als bedrijf? Neem dan contact op."),
        ("Hoe koop ik via de veiling?", "Onze planten gaan via Royal FloraHolland. Om daar te kopen moet je lid zijn. Bestellen gaat via Floriday."),
        ("Wanneer zijn Perovskia en Hibiscus er?", "Perovskia van mei tot september, Hibiscus in de zomer. Sempervivum is ons hoofdproduct."),
        ("Hoe lang kweken jullie een succulent?", "Zes tot acht maanden. We beginnen met eigen stek en potten over naar een pot van 12 tot 18 cm."),
        ("Waar gaan jullie planten naartoe?", "Naar inkopers in onder meer Scandinavië, Engeland, Duitsland en Zuid-Europa."),
    ],
    # contact
    "contact_h2": "Benieuwd wat er nu in de kas staat?",
    "contact_lede": "Bel of mail ons voor beschikbaarheid, de veiling of maatwerk.",
    "call": "Bel {phone}",
    "mail": "Mail ons",
    "nap_phone": "Telefoon",
    "nap_mail": "E-mail",
    "nap_address": "Adres",
    "country": "",
    "kvk": "KvK {kvk}",
    # plantpagina's
    "back_home": "← Terug naar de homepage",
    "crumb_home": "Home",
    "page_cta_buy": "Zo koop je bij ons",
    "gallery_h2": "Uit onze kas",
    "gallery_scribble": "eigen foto's",
    "pages": {
        "sempervivum": {
            "title": "Sempervivum-kweker: Chick Charms®, Giants en Colorockz® | Roots",
            "desc": "Roots kweekt Sempervivum (huislook) van eigen stek in IJsselmuiden: Chick Charms®, Chick Charms® Giants en Colorockz®, in pot 12–18 cm. Via Royal FloraHolland of direct.",
            "badge": "Ons hoofdproduct",
            "h1": "Sempervivum",
            "lede": "Winterharde succulenten in veel kleuren, van eigen stek gekweekt in onze kas in IJsselmuiden.",
            "facts": ["Pot 12–18 cm", "6–8 maanden", "Eigen stek", "Veiling of direct"],
            "series_h2": "Onze series",
            "series_scribble": "drie soorten huislook",
            "gallery_alts": [
                "Een rood-gele Sempervivum in pot, met een kas vol dezelfde planten erachter",
                "Een Sempervivum in pot in de hand, met een kastafel vol planten erachter",
                "Verkoopklare Sempervivum in pot op de kastafel",
                "Een kar vol Sempervivum in trays, met etiketten, klaar voor de order",
            ],
        },
        "perovskia": {
            "title": "Perovskia (Russische salie) kweker | Roots IJsselmuiden",
            "desc": "Roots kweekt Perovskia, Russische salie met lavendelpaarse bloei, bij ons van mei tot september. Kwekerij in IJsselmuiden, verkoop via Royal FloraHolland of direct.",
            "badge": "Mei – september",
            "h1": "Perovskia",
            "lede": "Russische salie met lavendelpaarse bloei. Bij ons van mei tot september.",
            "facts": ["Mei – september", "Veiling of direct"],
            "photos_h2": "Perovskia bij Roots",
            "photos_scribble": "in het seizoen",
            "alts": ["Perovskia Prime Time: Russische salie met lavendelpaarse bloei", "Stefan en Christel bij de kas, met Perovskia in pot"],
        },
        "hibiscus": {
            "title": "Hibiscus kweker | Roots IJsselmuiden",
            "desc": "Roots kweekt Hibiscus, een zomerbloeier met grote bloemen, in de zomer. Kwekerij in IJsselmuiden, verkoop via Royal FloraHolland of direct.",
            "badge": "Zomer",
            "h1": "Hibiscus",
            "lede": "Zomerbloeier met grote bloemen, in de zomer bij ons verkrijgbaar.",
            "facts": ["Zomer", "Veiling of direct"],
            "photos_h2": "Hibiscus bij Roots",
            "photos_scribble": "in de zomer",
            "alts": ["Hibiscus met grote witte bloem"],
        },
    },
    "nf_title": "Pagina niet gevonden | Roots",
    "nf_h1": "Deze pagina bestaat niet.",
    "nf_p": "Misschien is hij verplaatst. Op de homepage vind je alles over onze planten.",
    "nf_btn": "Naar de homepage",
},
# ------------------------------------------------------------------ ENGLISH
"en": {
    "skip": "Skip to content",
    "brand_label": "Roots, to the homepage",
    "menu_label": "Main menu",
    "lang_label": "Language",
    "nav": {"process": "How we grow", "plants": "Plants", "about": "About us", "buy": "Buying"},
    "contact_btn": "Contact",
    "home_title": "Roots | Sempervivum grower in the Netherlands",
    "home_desc": "Roots grows Sempervivum (Chick Charms®, Giants, Colorockz®), Perovskia and Hibiscus in IJsselmuiden, the Netherlands. Sempervivum from our own cuttings, sold via Royal FloraHolland or direct.",
    "badge": "Nursery in IJsselmuiden, NL · since 2021",
    "h1": "Strong succulents for your range.",
    "lede": "Sempervivum, Perovskia and Hibiscus from our own nursery. Buy through Royal FloraHolland or directly from us.",
    "cta_plants": "See our plants",
    "cta_buy": "How to buy",
    "ticker_label": "What we grow",
    "proc_h2": "From cutting to customer",
    "proc_scribble": "into the soil, out of the greenhouse",
    "proc_intro": "A good root first, the rest follows. Open a step to read more.",
    "group_in": "Into the greenhouse",
    "group_out": "Out of the greenhouse",
    "steps": [
        {"title": "Our own cuttings", "chips": [], "text": "Our succulents start as cuttings we take ourselves."},
        {"title": "Rooting", "chips": [], "text": "Each cutting first gets time to build a strong root system, hence our name.",
         "alt": "A rooted Sempervivum cutting held in a hand, roots visible, above a table full of young plants"},
        {"title": "Potting", "chips": ["Pot 12–18 cm"], "text": "Then the plant moves into its final pot.",
         "alt": "A potted Sempervivum held in a hand, with a greenhouse bench full of plants behind it"},
        {"title": "Growing in the greenhouse", "chips": ["6–8 months", "Minerals and fertiliser"], "text": "The plant grows to full size in our greenhouse in IJsselmuiden.",
         "alt": "A red and yellow Sempervivum in a pot, with a greenhouse full of the same plants behind it"},
        {"title": "Preparing orders", "chips": [], "text": "Once the plant is fully grown, we prepare it for orders.",
         "alt": "A trolley full of labelled Sempervivum in trays, ready for orders"},
        {"title": "Auction or direct", "chips": ["Floriday", "Direct"], "text": "We sell through the Royal FloraHolland auction or directly to the buyer.",
         "alt": "Sempervivum in pots, ready for sale, on a greenhouse bench"},
        {"title": "On the road", "chips": [], "text": "Through the auction the plants go into distribution, to Scandinavia, England, Germany and Southern Europe, among others.",
         "alt": "A flower transport lorry at the nursery in the morning light"},
    ],
    "plants_h2": "Our plants",
    "plants_scribble": "Sempervivum first",
    "plants_intro": "Sempervivum is our main product. In season we also grow Perovskia and Hibiscus.",
    "prev": "Previous plants",
    "next": "Next plants",
    "cards_label": "Plants",
    "credit": "Plant photos: Plantipp",
    "series": {
        "chick-charms": {"name": "Chick Charms®", "tag": "Sempervivum", "text": "Sempervivum in many colours.", "alt": "Sempervivum Chick Charms Gold Rush: rosettes in gold and red"},
        "giants": {"name": "Chick Charms® Giants", "tag": "Sempervivum", "text": "Chick Charms with extra-large rosettes.", "alt": "Sempervivum Chick Charms Giants Emerald Explosion: a large rosette in a green pot"},
        "colorockz": {"name": "Colorockz®", "tag": "Sempervivum", "text": "Sturdy Sempervivum that changes colour with the seasons.", "alt": "Sempervivum Colorockz Lemon Flare: full rosettes in green with red tips"},
        "perovskia": {"name": "Perovskia", "tag": "May – September", "text": "Russian sage with lavender-purple flowers.", "alt": "Perovskia Prime Time: Russian sage with lavender-purple flowers"},
        "hibiscus": {"name": "Hibiscus", "tag": "Summer", "text": "Summer bloomer with large flowers.", "alt": "Hibiscus with a large white flower"},
    },
    "about_h2": "Our roots",
    "about_scribble": "raised in horticulture",
    "about_p": "Stefan and Christel started Roots in 2021. In 2022 they bought the greenhouse on Hartogsweg in IJsselmuiden.",
    "about_more": "Read our story",
    "about_story": "Stefan grew up in horticulture: on a 600,000 m² rose nursery and in horticulture in Africa. They started small, but the greenhouse soon filled up. That growth never came at the expense of quality: from the first cutting to the plant on the trolley, they pay attention to every detail.",
    "people": [
        {"name": "Stefan", "role": "Owner", "text": "Day-to-day management, growth, strategy, sales, purchasing and staff."},
        {"name": "Christel", "role": "Partner", "text": "Strategy and bookkeeping."},
    ],
    "about_small": "In the busy months, school students and seasonal workers help us out.",
    "about_alt": "Stefan and Christel at the greenhouse, holding potted Perovskia",
    "buy_h2": "How to buy from us",
    "buy_scribble": "auction or direct",
    "buy_cards": [
        {"title": "Through the auction", "text": "Buy through Royal FloraHolland: you need to be a member, and orders go through Floriday."},
        {"title": "Direct", "text": "Call or email us to hear what is in the greenhouse right now."},
        {"title": "Custom orders", "text": "Get in touch for something made to order, for business or private use."},
    ],
    "dest_label": "Some of the places our plants go",
    "dest": {"n": ("Scandinavia", "North"), "w": ("England", "West"), "e": ("Germany", "East"), "s": ("Southern Europe", "South")},
    "faq_h2": "Good to know",
    "faq": [
        ("Can I buy from you as a private customer?", "Not usually: most of our customers are trade buyers. Looking for something made to order, privately or for your business? Then get in touch."),
        ("How do I buy through the auction?", "Our plants are sold through Royal FloraHolland. To buy there you need to be a member. Orders go through Floriday."),
        ("When are Perovskia and Hibiscus available?", "Perovskia from May to September, Hibiscus in summer. Sempervivum is our main product."),
        ("How long do you grow your succulents for?", "Six to eight months. We start from our own cuttings and pot them on into a 12 to 18 cm pot."),
        ("Where do your plants go?", "To buyers in Scandinavia, England, Germany and Southern Europe, among others."),
    ],
    "contact_h2": "Want to know what's in the greenhouse now?",
    "contact_lede": "Call or email us about availability, the auction or custom orders.",
    "call": "Call {phone}",
    "mail": "Email us",
    "nap_phone": "Phone",
    "nap_mail": "Email",
    "nap_address": "Address",
    "country": "The Netherlands",
    "kvk": "Chamber of Commerce (KvK) {kvk}",
    "back_home": "← Back to the homepage",
    "crumb_home": "Home",
    "page_cta_buy": "How to buy",
    "gallery_h2": "From our greenhouse",
    "gallery_scribble": "our own photos",
    "pages": {
        "sempervivum": {
            "title": "Sempervivum grower: Chick Charms®, Giants and Colorockz® | Roots",
            "desc": "Roots grows Sempervivum (houseleek) from its own cuttings in the Netherlands: Chick Charms®, Chick Charms® Giants and Colorockz®, in 12–18 cm pots. Via Royal FloraHolland or direct.",
            "badge": "Our main product",
            "h1": "Sempervivum",
            "lede": "Hardy succulents in many colours, grown from our own cuttings in our greenhouse in IJsselmuiden.",
            "facts": ["Pot 12–18 cm", "6–8 months", "Own cuttings", "Auction or direct"],
            "series_h2": "Our series",
            "series_scribble": "three kinds of houseleek",
            "gallery_alts": [
                "A red and yellow Sempervivum in a pot, with a greenhouse full of the same plants behind it",
                "A potted Sempervivum held in a hand, with a greenhouse bench full of plants behind it",
                "Sempervivum in pots, ready for sale, on a greenhouse bench",
                "A trolley full of labelled Sempervivum in trays, ready for orders",
            ],
        },
        "perovskia": {
            "title": "Perovskia (Russian sage) grower | Roots, the Netherlands",
            "desc": "Roots grows Perovskia, Russian sage with lavender-purple flowers, available May to September. Nursery in IJsselmuiden, the Netherlands; sold via Royal FloraHolland or direct.",
            "badge": "May – September",
            "h1": "Perovskia",
            "lede": "Russian sage with lavender-purple flowers. Available from May to September.",
            "facts": ["May – September", "Auction or direct"],
            "photos_h2": "Perovskia at Roots",
            "photos_scribble": "in season",
            "alts": ["Perovskia Prime Time: Russian sage with lavender-purple flowers", "Stefan and Christel at the greenhouse, holding potted Perovskia"],
        },
        "hibiscus": {
            "title": "Hibiscus grower | Roots, the Netherlands",
            "desc": "Roots grows Hibiscus, a summer bloomer with large flowers, in summer. Nursery in IJsselmuiden, the Netherlands; sold via Royal FloraHolland or direct.",
            "badge": "Summer",
            "h1": "Hibiscus",
            "lede": "A summer bloomer with large flowers, available from us in summer.",
            "facts": ["Summer", "Auction or direct"],
            "photos_h2": "Hibiscus at Roots",
            "photos_scribble": "in summer",
            "alts": ["Hibiscus with a large white flower"],
        },
    },
    "nf_title": "Page not found | Roots",
    "nf_h1": "This page does not exist.",
    "nf_p": "It may have moved. The homepage has everything about our plants.",
    "nf_btn": "To the homepage",
},
# ------------------------------------------------------------------ DEUTSCH
"de": {
    "skip": "Zum Inhalt",
    "brand_label": "Roots, zur Startseite",
    "menu_label": "Hauptmenü",
    "lang_label": "Sprache",
    "nav": {"process": "Anbau", "plants": "Pflanzen", "about": "Über uns", "buy": "Einkauf"},
    "contact_btn": "Kontakt",
    "home_title": "Roots | Sempervivum-Gärtnerei in den Niederlanden",
    "home_desc": "Roots kultiviert Sempervivum (Chick Charms®, Giants, Colorockz®), Perovskia und Hibiskus in IJsselmuiden, Niederlande. Sempervivum aus eigenen Stecklingen, Verkauf über Royal FloraHolland oder direkt.",
    "badge": "Gärtnerei in IJsselmuiden (NL) · seit 2021",
    "h1": "Starke Sukkulenten für Ihr Sortiment.",
    "lede": "Sempervivum, Perovskia und Hibiskus aus eigener Gärtnerei. Kaufen Sie über Royal FloraHolland oder direkt bei uns.",
    "cta_plants": "Unsere Pflanzen",
    "cta_buy": "So kaufen Sie bei uns",
    "ticker_label": "Was wir kultivieren",
    "proc_h2": "Vom Steckling zum Kunden",
    "proc_scribble": "in die Erde, aus dem Gewächshaus",
    "proc_intro": "Erst eine gute Wurzel, der Rest folgt. Öffnen Sie einen Schritt für mehr.",
    "group_in": "Ins Gewächshaus",
    "group_out": "Aus dem Gewächshaus",
    "steps": [
        {"title": "Eigene Stecklinge", "chips": [], "text": "Unsere Sukkulenten beginnen als Stecklinge, die wir selbst schneiden."},
        {"title": "Bewurzeln", "chips": [], "text": "Jeder Steckling bekommt zuerst Zeit für ein starkes Wurzelwerk, daher unser Name.",
         "alt": "Ein bewurzelter Sempervivum-Steckling in der Hand, die Wurzeln sichtbar, über einem Tisch voller Jungpflanzen"},
        {"title": "Eintopfen", "chips": ["Topf 12–18 cm"], "text": "Danach kommt die Pflanze in ihren endgültigen Topf.",
         "alt": "Ein Sempervivum im Topf in der Hand, dahinter ein Gewächshaustisch voller Pflanzen"},
        {"title": "Wachsen im Gewächshaus", "chips": ["6–8 Monate", "Mineralien und Dünger"], "text": "In unserem Gewächshaus in IJsselmuiden wächst die Pflanze heran.",
         "alt": "Ein rot-gelbes Sempervivum im Topf, dahinter ein Gewächshaus voller gleicher Pflanzen"},
        {"title": "Vorbereiten", "chips": [], "text": "Ist die Pflanze ausgewachsen, machen wir sie für die Bestellung fertig.",
         "alt": "Ein Wagen voller etikettierter Sempervivum in Trays, bereit für die Bestellung"},
        {"title": "Versteigerung oder direkt", "chips": ["Floriday", "Direkt"], "text": "Wir verkaufen über die Versteigerung von Royal FloraHolland oder direkt an den Käufer.",
         "alt": "Verkaufsfertige Sempervivum im Topf auf dem Gewächshaustisch"},
        {"title": "Unterwegs", "chips": [], "text": "Über die Versteigerung gehen die Pflanzen in den Vertrieb, unter anderem nach Skandinavien, England, Deutschland und Südeuropa.",
         "alt": "Ein Lkw für Blumentransporte an der Gärtnerei im Morgenlicht"},
    ],
    "plants_h2": "Unsere Pflanzen",
    "plants_scribble": "Sempervivum zuerst",
    "plants_intro": "Sempervivum ist unser Hauptprodukt. In der Saison kultivieren wir auch Perovskia und Hibiskus.",
    "prev": "Vorherige Pflanzen",
    "next": "Nächste Pflanzen",
    "cards_label": "Pflanzen",
    "credit": "Pflanzenfotos: Plantipp",
    "series": {
        "chick-charms": {"name": "Chick Charms®", "tag": "Sempervivum", "text": "Sempervivum in vielen Farben.", "alt": "Sempervivum Chick Charms Gold Rush: Rosetten in Gold und Rot"},
        "giants": {"name": "Chick Charms® Giants", "tag": "Sempervivum", "text": "Chick Charms mit extra großen Rosetten.", "alt": "Sempervivum Chick Charms Giants Emerald Explosion: große Rosette in einem grünen Topf"},
        "colorockz": {"name": "Colorockz®", "tag": "Sempervivum", "text": "Robuste Sempervivum, die mit den Jahreszeiten die Farbe wechseln.", "alt": "Sempervivum Colorockz Lemon Flare: volle Rosetten in Grün mit roten Spitzen"},
        "perovskia": {"name": "Perovskia", "tag": "Mai – September", "text": "Blauraute mit lavendelvioletten Blüten.", "alt": "Perovskia Prime Time: Blauraute mit lavendelvioletten Blüten"},
        "hibiscus": {"name": "Hibiskus", "tag": "Sommer", "text": "Sommerblüher mit großen Blüten.", "alt": "Hibiskus mit großer weißer Blüte"},
    },
    "about_h2": "Unsere Wurzeln",
    "about_scribble": "im Gartenbau aufgewachsen",
    "about_p": "Stefan und Christel haben Roots 2021 gegründet. 2022 kauften sie das Gewächshaus am Hartogsweg in IJsselmuiden.",
    "about_more": "Unsere Geschichte",
    "about_story": "Stefan ist im Gartenbau aufgewachsen: auf einer Rosengärtnerei mit 600.000 m² und im Gartenbau in Afrika. Gemeinsam haben sie klein angefangen, doch schon bald war das Gewächshaus voll. Dieses Wachstum ging nie auf Kosten der Qualität: Vom ersten Steckling bis zur Pflanze auf dem Wagen achten sie auf jedes Detail.",
    "people": [
        {"name": "Stefan", "role": "Inhaber", "text": "Tägliche Leitung, Wachstum, Strategie, Verkauf, Einkauf und Personal."},
        {"name": "Christel", "role": "Strategie & Buchhaltung", "text": "Hat Roots 2021 gemeinsam mit Stefan gegründet."},
    ],
    "about_small": "In den arbeitsreichen Monaten helfen uns Schüler und Saisonkräfte.",
    "about_alt": "Stefan und Christel am Gewächshaus, mit Perovskia im Topf",
    "buy_h2": "So kaufen Sie bei uns",
    "buy_scribble": "Versteigerung oder direkt",
    "buy_cards": [
        {"title": "Über die Versteigerung", "text": "Kaufen Sie über Royal FloraHolland: Dafür brauchen Sie eine Mitgliedschaft, bestellt wird über Floriday."},
        {"title": "Direkt", "text": "Rufen Sie an oder schreiben Sie uns, um zu erfahren, was gerade im Gewächshaus steht."},
        {"title": "Sonderwünsche", "text": "Kontaktieren Sie uns für individuelle Wünsche, geschäftlich oder privat."},
    ],
    "dest_label": "Unsere Pflanzen gehen unter anderem nach",
    "dest": {"n": ("Skandinavien", "Nord"), "w": ("England", "West"), "e": ("Deutschland", "Ost"), "s": ("Südeuropa", "Süd")},
    "faq_h2": "Gut zu wissen",
    "faq": [
        ("Kann ich als Privatperson bei Ihnen kaufen?", "Kaum: Unsere Kunden sind vor allem gewerbliche Einkäufer. Suchen Sie etwas Individuelles, privat oder geschäftlich? Dann nehmen Sie Kontakt mit uns auf."),
        ("Wie kaufe ich über die Versteigerung?", "Unsere Pflanzen werden über Royal FloraHolland verkauft. Um dort zu kaufen, brauchen Sie eine Mitgliedschaft. Bestellt wird über Floriday."),
        ("Wann gibt es Perovskia und Hibiskus?", "Perovskia von Mai bis September, Hibiskus im Sommer. Sempervivum ist unser Hauptprodukt."),
        ("Wie lange wächst eine Sukkulente bei Ihnen?", "Sechs bis acht Monate. Wir beginnen mit eigenen Stecklingen und topfen sie in einen Topf von 12 bis 18 cm um."),
        ("Wohin gehen Ihre Pflanzen?", "Zu Einkäufern unter anderem in Skandinavien, England, Deutschland und Südeuropa."),
    ],
    "contact_h2": "Was steht gerade im Gewächshaus?",
    "contact_lede": "Rufen Sie an oder schreiben Sie uns: Verfügbarkeit, Versteigerung oder Sonderwünsche.",
    "call": "Anrufen: {phone}",
    "mail": "E-Mail schreiben",
    "nap_phone": "Telefon",
    "nap_mail": "E-Mail",
    "nap_address": "Adresse",
    "country": "Niederlande",
    "kvk": "Handelsregister (KvK) {kvk}",
    "back_home": "← Zurück zur Startseite",
    "crumb_home": "Startseite",
    "page_cta_buy": "So kaufen Sie bei uns",
    "gallery_h2": "Aus unserem Gewächshaus",
    "gallery_scribble": "eigene Fotos",
    "pages": {
        "sempervivum": {
            "title": "Sempervivum-Gärtnerei: Chick Charms®, Giants und Colorockz® | Roots",
            "desc": "Roots kultiviert Sempervivum (Hauswurz) aus eigenen Stecklingen in den Niederlanden: Chick Charms®, Chick Charms® Giants und Colorockz®, im Topf 12–18 cm. Über Royal FloraHolland oder direkt.",
            "badge": "Unser Hauptprodukt",
            "h1": "Sempervivum",
            "lede": "Winterharte Sukkulenten in vielen Farben, aus eigenen Stecklingen in unserem Gewächshaus in IJsselmuiden gezogen.",
            "facts": ["Topf 12–18 cm", "6–8 Monate", "Eigene Stecklinge", "Versteigerung oder direkt"],
            "series_h2": "Unsere Serien",
            "series_scribble": "drei Serien Hauswurz",
            "gallery_alts": [
                "Ein rot-gelbes Sempervivum im Topf, dahinter ein Gewächshaus voller gleicher Pflanzen",
                "Ein Sempervivum im Topf in der Hand, dahinter ein Gewächshaustisch voller Pflanzen",
                "Verkaufsfertige Sempervivum im Topf auf dem Gewächshaustisch",
                "Ein Wagen voller etikettierter Sempervivum in Trays, bereit für die Bestellung",
            ],
        },
        "perovskia": {
            "title": "Perovskia-Gärtnerei (Blauraute) | Roots, Niederlande",
            "desc": "Roots kultiviert Perovskia, Blauraute mit lavendelvioletten Blüten, bei uns von Mai bis September. Gärtnerei in IJsselmuiden, Niederlande; Verkauf über Royal FloraHolland oder direkt.",
            "badge": "Mai – September",
            "h1": "Perovskia",
            "lede": "Blauraute mit lavendelvioletten Blüten. Bei uns von Mai bis September.",
            "facts": ["Mai – September", "Versteigerung oder direkt"],
            "photos_h2": "Perovskia bei Roots",
            "photos_scribble": "in der Saison",
            "alts": ["Perovskia Prime Time: Blauraute mit lavendelvioletten Blüten", "Stefan und Christel am Gewächshaus, mit Perovskia im Topf"],
        },
        "hibiscus": {
            "title": "Hibiskus-Gärtnerei | Roots, Niederlande",
            "desc": "Roots kultiviert Hibiskus, einen Sommerblüher mit großen Blüten, im Sommer. Gärtnerei in IJsselmuiden, Niederlande; Verkauf über Royal FloraHolland oder direkt.",
            "badge": "Sommer",
            "h1": "Hibiskus",
            "lede": "Sommerblüher mit großen Blüten, bei uns im Sommer erhältlich.",
            "facts": ["Sommer", "Versteigerung oder direkt"],
            "photos_h2": "Hibiskus bei Roots",
            "photos_scribble": "im Sommer",
            "alts": ["Hibiskus mit großer weißer Blüte"],
        },
    },
    "nf_title": "Seite nicht gefunden | Roots",
    "nf_h1": "Diese Seite gibt es nicht.",
    "nf_p": "Vielleicht wurde sie verschoben. Auf der Startseite finden Sie alles über unsere Pflanzen.",
    "nf_btn": "Zur Startseite",
},
}
